const WindowBar=({label,status}:{label:string;status:string})=><div className="surface-bar"><span>● ● ●</span><b>cuepa · {label}</b><em>{status}</em></div>;
const CheckIcon=()=> <svg viewBox="0 0 16 16" aria-hidden><path d="m3 8.3 3 3L13 4.8"/></svg>;

const MapView=()=> <div className="product-surface ecosystem-surface"><WindowBar label="room map" status="DRAFT — FOR YOUR OK"/><div className="surface-body"><h3>How work moves — mapped.</h3><small>11 workflows observed · 6 people heard</small>{[["Invoicing & billing","AUTOMATE"],["Lead follow-up","AUTOMATE"],["Client relationships","STAYS HUMAN"],["Client records","PROTECTED"]].map((x,i)=><div className="map-row" key={x[0]}><div><b>{x[0]}</b><small>{["rebuilt by hand every week","42 min average response","the part only you can do","access never leaves your control"][i]}</small></div><span className={i===2?"human":i===3?"protected":""}>{x[1]}</span></div>)}<div className="room-found"><small>ROOM FOUND</small><strong>11.5 <i>hrs / week</i></strong><div/><p><b>Nothing is built until you approve it.</b></p></div></div></div>;

const ReportView=()=> <div className="product-surface ecosystem-surface"><WindowBar label="room report" status="VERIFIED"/><div className="surface-body"><h3>Your room, before → after</h3><small>Measured against the baseline from week one</small><div className="report-row"><b>Lead response</b><span><s>42 min</s> → <strong>4 min</strong></span></div><div className="report-row"><b>Hours returned</b><span><s>0</s> → <strong>11.5 hrs</strong></span></div><div className="report-row"><b>Invoice errors</b><span><s>?</s> → <strong>17 caught</strong></span></div><div className="verified-note"><b><CheckIcon/>Verified against baseline.</b><span>Every number ties to a measurement taken before we built anything.</span></div><div className="ecosystem-opportunity"><small>GROW · OPPORTUNITY FOUND</small><strong>$3,180 in unbilled work</strong><p>Across 4 clients. Invoices drafted for review.</p></div></div></div>;

const ControlView=()=> <div className="product-surface ecosystem-surface"><WindowBar label="owner control" status="3 NEED YOU"/><div className="surface-body"><div className="dashboard-head"><div><h3>Good evening, Marcos.</h3><p>3 things need you. Everything else is handled.</p></div><span>LIVE</span></div><div className="compact-metrics"><article><small>HOURS RETURNED</small><strong>11.5</strong></article><article><small>FLOW SUCCESS</small><strong>98.7%</strong></article><article><small>NEEDS YOU</small><strong>3</strong></article></div><div className="approval-row compact-approval"><div><small>READY FOR YOUR SIGN-OFF</small><strong>$2,805 · contractor payout</strong><p className="evidence-line">Protected · details masked <CheckIcon/> Challenged · matched to estimate</p></div><button>Approve</button><button className="hold">Hold</button></div></div></div>;

export function ProductEcosystem(){return <section className="ecosystem" id="proof"><div className="shell"><header className="ecosystem-heading"><div><p className="eyebrow">One system · Three connected views</p><h2>See the work.<br/>Prove the result.</h2></div><p>Room Map, Room Report, and Owner Control follow the same work from observation to evidence to your final decision.</p></header><div className="ecosystem-thread" aria-hidden><i/><i/><i/></div><div className="ecosystem-grid"><article><header><span>01</span><div><small>FIND</small><h3>Room Map</h3></div></header><p>What can move, what stays human, and what must be protected.</p><MapView/></article><article><header><span>02</span><div><small>PROVE / GROW</small><h3>Room Report</h3></div></header><p>What changed, how it was verified, and where opportunity returned.</p><ReportView/></article><article><header><span>03</span><div><small>YOUR DECISION</small><h3>Owner Control</h3></div></header><p>Everything CUEPA moved—and the few decisions that still need you.</p><ControlView/></article></div></div></section>}
